type: app
description: Default stackfile usecase description
template: pipeline-dados/terraform
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: pipeline-dados/aws-start-rds-snapshot-plugin